#!/usr/bin/env Rscript

###############################
#    RAS Modifiers Project    #
###############################

# Copyright (c) 2023-Present Ryan L. Collins and the Van Allen/Gusev/Haigis Laboratories
# Distributed under terms of the GNU GPL v2.0 License (see LICENSE)
# Contact: Ryan L. Collins <Ryan_Collins@dfci.harvard.edu>

# Plot comparisons of somatic mutation frequencies between cohorts & cancer types


#########
# Setup #
#########
# Load necessary libraries and constants
require(OncoModR, quietly=TRUE)
require(argparse, quietly=TRUE)
require(Hmisc, quietly=TRUE)
OncoModR::load.constants("all")


##################
# Data functions #
##################
# Load & clean somatic frequency data from .tsv
load.somatic.freqs <- function(tsv.in){
  # Read data into memory
  data <- read.table(tsv.in, sep="\t", comment.char="", check.names=F, header=T)
  data$csq.simple <- paste(data$ref, data$codon, data$alt, sep="")
  data$csq.simple[which(data$alt == "AMP")] <- "AMP"
  data$csq.simple[which(data$alt == "DEL")] <- "DEL"
  rownames(data) <- data$csq.simple

  # Only keep frequency data
  data <- data[, grep("_AN$|_AF$|_AC$", colnames(data))]

  # Compute 95% binomial CIs for all points
  for(cidx in grep("_AF$", colnames(data))){
    prefix <- gsub("_AF$", "", colnames(data)[cidx])
    ci <- binconf(x=data[, paste(prefix, "AC", sep="_")],
            n=data[, paste(prefix, "AN", sep="_")],
            method="exact", return.df=TRUE)[, c("Lower", "Upper")]
    colnames(ci) <- paste(prefix, "AF", c("lower", "upper"), sep="_")
    data <- cbind(data, ci)
  }

  # Return sorted df
  data[, sort(colnames(data))]
}


######################
# Plotting functions #
######################
# Scatterplot of mutation frequency correlations between two cohorts
plot.somatic.freq.scatter <- function(data, p1, p2, pair.names, cancer,
                                      label.top.n=5){
  # Prepare plot area
  max.freq <- max(data[, paste(c(p1, p2), "AF", sep="_")], na.rm=T)
  ax.lims <- c(0, min(c(1.5 * max.freq, 1)))
  prep.plot.area(xlims=ax.lims, ylims=ax.lims, parmar=c(2.75, 2.75, 1.25, 1.25))
  sapply(1:2, function(k){
    clean.axis(k, title=paste(pair.names[k], "Frequency"), infinite=T,
               labels=paste(100 * axTicks(k), "%", sep=""),
               title.line=if(k==1){0.5}else{0.85})
  })
  mtext(paste(pair.names[1], " vs. ", pair.names[2], " (",
              cancer.names.short[cancer], ")", sep=""), 3, line=0.25)
  abline(0, 1, col="gray50")

  # Add confidence intervals then points
  segments(x0=data[, paste(p1, "AF", sep="_")],
           x1=data[, paste(p1, "AF", sep="_")],
           y0=data[, paste(p2, "AF_lower", sep="_")],
           y1=data[, paste(p2, "AF_upper", sep="_")],
           col="gray75")
  segments(x0=data[, paste(p1, "AF_lower", sep="_")],
           x1=data[, paste(p1, "AF_upper", sep="_")],
           y0=data[, paste(p2, "AF", sep="_")],
           y1=data[, paste(p2, "AF", sep="_")],
           col="gray75")
  points(x=data[, paste(p1, "AF", sep="_")],
         y=data[, paste(p2, "AF", sep="_")],
         pch=19, col=cancer.colors[cancer])

  # If optioned, label mutation csq for top N points
  max.freq.order <- order(apply(data[, paste(c(p1, p2), "AF", sep="_")], 1, max, na.rm=T),
                          decreasing=T)
  if(label.top.n > 0){
    sapply(1:label.top.n, function(i){
      xpos <- data[max.freq.order[i], paste(p1, "AF", sep="_")]
      ypos <-data[max.freq.order[i], paste(p2, "AF", sep="_")]
      lab.pos <- if(xpos > ypos){3}else{1}
      text(x=xpos, y=ypos, pos=lab.pos, cex=5/6,
           labels=rownames(data)[max.freq.order[i]])
    })
  }
}


###########
# RScript #
###########
# Parse command line arguments and options
parser <- ArgumentParser(description=paste("Plot comparisons of somatic mutation",
                                           "frequencies between cohorts and cancers"))
parser$add_argument("--stats", metavar=".tsv", type="character", required=TRUE,
                    help=paste("somatic mutation frequency .tsv generated by",
                               "gather_somatic_ras_data.py"))
parser$add_argument('--out-prefix', metavar='path', type="character", nargs=1,
                    help='file prefix for all plots')
args <- parser$parse_args()

# # DEV
# args <- list("stats"="~/scratch/ras_somatic_variants.tsv.gz",
#              "out_prefix"="~/scratch/somatic_freq_cor_test")

# Load somatic mutation frequency data
data <- load.somatic.freqs(args$stats)


################################################
# Inter-cohort comparisons within cancer types #
################################################
cohorts <- sort(unique(unlist(sapply(strsplit(colnames(data), split="_"), function(l){l[1]}))))
cancers <- sort(unique(unlist(sapply(strsplit(colnames(data), split="_"), function(l){l[2]}))))
apply(combn(cohorts, 2), 2, function(pair.names){
  # One plot per cancer type
  sapply(cancers, function(cancer){
    col.prefixes <- paste(pair.names, cancer, sep="_")
    png(paste(args$out_prefix, "kras_somatic_intercohort_comparison",
              pair.names[1], pair.names[2], cancer, "png", sep="."),
        height=3*300, width=3*300, res=300)
    plot.somatic.freq.scatter(data, p1=col.prefixes[1], p2=col.prefixes[2],
                              pair.names, cancer, label.top.n=4)
    dev.off()
  })
})

