#!/usr/bin/env R

###############################
#    RAS Modifiers Project    #
###############################

# Copyright (c) 2023-Present Ryan L. Collins and the Van Allen/Gusev/Haigis Laboratories
# Distributed under terms of the GNU GPL v2.0 License (see LICENSE)
# Contact: Ryan L. Collins <Ryan_Collins@dfci.harvard.edu>

# Meta-analysis functions


#' Load association stats
#'
#' Load germline-somatic association statistics from a single cohort
#'
#' @param file Path to input stats .tsv
#' @param suffix Suffix to append to all columns \[default: NULL\]
#' @param suffix.skip Number vector indicating which columns to skip when
#' suffixing \[default: 1-2\]
#'
#' @return data.frame
#'
#' @export load.assoc.stats.single
#' @export
load.assoc.stats.single <- function(file, suffix=NULL, suffix.skip=1:2){
  df <- read.table(file, check.names=F, comment.char="", sep="\t", header=T)
  colnames(df)[1] <- gsub("^#", "", colnames(df)[1])
  if(!is.null(suffix)){
    colnames(df)[-suffix.skip] <- paste(colnames(df)[-suffix.skip], suffix, sep=".")
  }
  df[, -suffix.skip] <- apply(df[, -suffix.skip], 2, as.numeric)
  return(df)
}


#' Merge association stats
#'
#' Merge association statistics across multiple cohorts
#'
#' @param stats.list List of single-cohort association statistics
#' as loaded using [load.assoc.stats.single]
#'
#' @return data.frame
#'
#' @seealso [load.assoc.stats.single]
#'
#' @export merge.assoc.stats
#' @export
merge.assoc.stats <- function(stats.list){
  # Iteratively outer join all stats
  merged <- Reduce(function(x, y){merge(x, y, all=T, by=c("somatic", "germline"), sort=F)},
                   stats.list)

  # Gather information on non-NA cohorts
  cohort.info <- as.data.frame(t(apply(merged[, grep("^z\\.", colnames(merged))], 1,
                                       function(zscores){
                                         idxs <- which(!is.na(zscores) & !is.infinite(zscores))
                                         cohorts <- names(stats.list)[idxs]
                                         c(length(cohorts), paste(sort(cohorts), collapse=","))
                                       })))
  colnames(cohort.info) <- c("N_cohorts", "cohorts")

  # Return merged data.frame
  cbind(merged, cohort.info)
}


#' Average variant frequencies
#'
#' Compute weighted average of variant frequencies for germline-somatic association stats
#'
#' @param df Merged data.frame of two or more cohorts \(see `Details`\)
#'
#' @details `df` should be a data.frame generated by [merge.assoc.stats]
#'
#' @return data.frame
#'
#' @seealso [load.assoc.stats.single], [merge.assoc.stats]
#'
#' @export merge.assoc.stats
#' @export
average.meta.freqs <- function(df){
  # Compute weighted variant frequencies
  wfreqs <- as.data.frame(t(apply(df, 1, function(rvals){
    samps <- as.numeric(rvals[grep("^samples\\.", names(rvals))])
    weights <- sqrt(samps)
    som.ac <- as.numeric(rvals[grep("^somatic_AC\\.", names(rvals))])
    som.freqs <- som.ac / samps
    som.freq.w <- weighted.mean(som.freqs, weights, na.rm=T)
    yes_som.germ.ac <- as.numeric(rvals[grep("^yes_somatic.germline_AC\\.", names(rvals))])
    yes_som.germ.freqs <- yes_som.germ.ac / (2 * samps)
    yes_som.germ.freq.w <- weighted.mean(yes_som.germ.freqs, weights, na.rm=T)
    no_som.germ.ac <- as.numeric(rvals[grep("^no_somatic.germline_AC\\.", names(rvals))])
    no_som.germ.freqs <- no_som.germ.ac / (2 * samps)
    no_som.germ.freq.w <- weighted.mean(no_som.germ.freqs, weights, na.rm=T)
    return(c(som.freq.w, yes_som.germ.freq.w, no_som.germ.freq.w))
  })))
  colnames(wfreqs) <- c("somatic_freq", "yes_somatic.germline_AF", "no_somatic.germline_AF")

  # Add weighted frequencies to df and drop all single-cohort freq info
  cols.to.drop <- grep("^samples\\.|^somatic_AC\\.|\\.germline_AC\\.", colnames(df))
  cbind(df[, -cols.to.drop], wfreqs)
}


#' Inverse-variance weighted meta-analysis
#'
#' Conduct an inverse-variance weighted meta-analysis of effect sizes
#'
#' @param x vector of observed effect sizes
#' @param se vector of observed standard errors
#'
#' @return named vector of meta-analysis effect size and standard error
#'
#' @export ivw.meta.single
#' @export
ivw.meta.single <- function(x, se){
  # Compute weights as
  vars <- se^2
  weights <- 1 / vars

  # Compute weighted mean
  x.bar <- weighted.mean(x, weights, na.rm=T)

  # Compute standard error of sum of weighted observations
  se.bar <- sqrt(1 / sum(weights, na.rm=T))

  return(c("statistic" = x.bar, "std.err" = se.bar))
}


#' Meta-analyze effect sizes
#'
#' Meta-analyze effect sizes of all germline-somatic associations
#'
#' @param df Merged data.frame of two or more cohorts \(see `Details`\)
#'
#' @details `df` should be a data.frame generated by [merge.assoc.stats]
#'
#' @return data.frame
#'
#' @seealso [load.assoc.stats.single], [merge.assoc.stats], [ivw.meta.single]
#'
#' @export ivw.meta.analysis
#' @export
ivw.meta.analysis <- function(df){
  # Meta-analyze effect sizes
  meta.stats <- as.data.frame(t(apply(df, 1, function(rvals){
    betas <- as.numeric(rvals[grep("^beta\\.", names(rvals))])
    ses <- as.numeric(rvals[grep("^beta_SE\\.", names(rvals))])
    ivw.meta.single(betas, ses)
  })))
  colnames(meta.stats) <- c("beta", "beta_SE")
  meta.stats$z <- meta.stats$beta / meta.stats$beta_SE
  meta.stats$p <- 2*pnorm(-abs(meta.stats$z))

  # Add meta-analysis stats to df and drop all single-cohort stats
  cols.to.drop <- grep("^beta\\.|^beta_SE\\.|^z\\.|^p\\.", colnames(df))
  df <- cbind(df[, -cols.to.drop], meta.stats)

  # Sort rows and reorder columns
  ideal.col.order <- c("somatic", "germline", "somatic_freq", "yes_somatic.germline_AF",
                       "no_somatic.germline_AF", "N_cohorts", "cohorts",
                       "beta", "beta_SE", "z", "p")
  df[with(df, order(somatic, germline)),
     intersect(ideal.col.order, colnames(df))]
}


